## Copyright (c) 2011 The WebM project authors. All Rights Reserved.
## 
## Use of this source code is governed by a BSD-style license
## that can be found in the LICENSE file in the root of the source
## tree. An additional intellectual property rights grant can be found
## in the file PATENTS.  All contributing project authors may
## be found in the AUTHORS file in the root of the source tree.
# This file automatically generated by configure. Do not edit!
TOOLCHAIN := generic-gnu
ALL_TARGETS += libs

PREFIX=/usr/local
ifeq ($(MAKECMDGOALS),dist)
DIST_DIR?=vpx-vp8dx-nopost-nomt-nodocs-generic-gnu-v1.4.0
else
DIST_DIR?=$(DESTDIR)/usr/local
endif
LIBSUBDIR=lib

VERSION_STRING=v1.4.0

VERSION_MAJOR=1
VERSION_MINOR=4
VERSION_PATCH=0

CONFIGURE_ARGS=--target=generic-gnu --disable-examples --disable-docs --disable-unit-tests --disable-vp8-encoder --disable-multithread --disable-vp9-decoder --disable-vp9-encoder
CONFIGURE_ARGS?=--target=generic-gnu --disable-examples --disable-docs --disable-unit-tests --disable-vp8-encoder --disable-multithread --disable-vp9-decoder --disable-vp9-encoder
